### PR TITLE
Add ssl configuration for doSendRequest and refactor

### PR DESCRIPTION
**Pull request by valashko**

### CODE REVIEW

**Comment by yglukhov** [comment]
Could you please explain the reason for this? If you need to disable verification, I'd just disable it once and for all until it is implemented in nim :)

**Comment by valashko** [comment]
Main reason for the change was making SSL configuration (via passing an `SslContext` object) in `sendRequest` possible. Rest of the changes tidy up existing code in order to achieve uniform behaviour.

**Comment by yglukhov** [comment]
My biggest concern so far is that `SslContext` might be passed across threads. I'm not sure if that's safe, since the context originates from the C lib.
At this point I suggest changing SslContext creation to `newContext(protVersion = protTLSv1, verifyMode = CVerifyNone)` unconditionally. Such configuration should satisfy all use cases I'm aware of.

**Comment by valashko** [comment]
The very reason this PR exists is adding a point of customization, which is absent at the moment. This implies that any defaulting that cannot be overridden renders it pointless. I have the following argument to satisfy your concern. Judjing from [net.nim](https://github.com/nim-lang/Nim/blob/master/lib/pure/net.nim#L90), `SslContext` is an object that can be safely used in another thread because according to `spawn` statement [documentation](https://nim-lang.org/docs/manual_experimental.html#parallel-amp-spawn-spawn-statement) "_...ref parameters are deeply copied..._". This means that:
- `context*: SslCtx` being essentially a pointer to `SSL_CTX` struct from _openssl_ is allocated on the **unmanaged** heap; everything on the heap is shared between threads
- `referencedData: HashSet[int]` is deeply copied and safe to use
- `extraInternal: SslContextExtraInternal` is deeply copied and safe to use

**Comment by yglukhov** [comment]
Ok, I guess you're right.

**Pull request merged**
